---
title: 'Tidy Tuesday - Week #29'
author: "Julia Tache"
date: '2022-07-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r load data}
library(tidyverse)
library(tidytuesdayR)
library(ggsankey)
library(scales)

tuesdata <- tidytuesdayR::tt_load('2022-07-19')
technology <- tuesdata$technology
```

```{r}
USA_vaccine <- technology %>%
  filter(category == "Vaccines") %>%
  filter(label != "Extracorporeal shock wave lithotripters") %>%
  filter(variable != "Hib3") %>%
  filter(variable != "MCV2") %>%
  filter(variable != "HepB3") %>%
  filter(variable != "IPV1") %>%
  filter(variable != "PCV3") %>%
  filter(variable != "RotaC") %>%
  filter(variable != "pctimmunizmeas") %>%
  filter(iso3c == "USA") %>%
  group_by(iso3c, year, variable) %>%
  summarize(n = mean(value))

USA_vaccine$variable <- str_replace(USA_vaccine$variable, "MCV1", "Measles")
USA_vaccine$variable <- str_replace(USA_vaccine$variable, "RCV1", "Rubella")
USA_vaccine$variable <- str_replace(USA_vaccine$variable, "Pol3", "Polio")

USA_vaccine$n <- USA_vaccine$n/100

ggplot(USA_vaccine, aes(x = year, y = n)) +
  geom_line() +
  geom_point(size = 0.5) +
  facet_wrap(~variable) +
  geom_vline(xintercept = 1998, color = "red") +
  geom_text(data = data.frame(x = 1999,
                              y = 0.85,
                              variable = "DPT",
                              label = "1998: \nLancet MMR paper is published"),
            aes(x = x, y = y, label = label), 
            size = 2, 
            hjust = 0,
            fontface = "italic") +
  ylab("Number of Flights") +
  labs(title = "Percent of Children who Received Immunizations in the U.S.",
       subtitle = "Strong convergence in use of consumption technologies, like vaccines, compared to production technologies, indicates increasing quality of life. \nDespite a deeply controversial paper linking vaccines to autism, vaccine rates nationwide have not greatly changed in the past decade.",
       caption = "Source: data.nber.org | github: julia-tache | July 25th, 2022") +
  theme(panel.background = element_rect(fill = "#E4FDE1"),
        plot.background = element_rect(fill = "#F3EAAF"),
        strip.background = element_rect(fill = "#648381"),
        strip.text = element_text(colour = 'white'),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, size = 7, face = "italic"),
        plot.caption = element_text(hjust = 0.5),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  scale_x_continuous(breaks = round(seq(min(USA_vaccine$year), max(USA_vaccine$year), by = 5), 1)) +
  scale_y_continuous(breaks = pretty_breaks(5),
                     labels = percent)

ggsave("immunizations.png")

```

