---
title: 'Tidy Tuesday - Week 14 (2025)'
author: "Julia Tache"
date: '2025-04-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}

library(tidyverse)
library(ggrepel)
library(tidytuesdayR)
library(urbnmapr)
library(geosphere)

```

```{r load and prep data}

care_state <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-04-08/care_state.csv")

care_state <- care_state %>%
  rename("state_abbv" = "state") %>%
  filter(state_abbv != "AS") %>%
  filter(state_abbv != "GU") %>%
  filter(state_abbv != "MP") %>%
  filter(state_abbv != "PR") %>%
  filter(state_abbv != "VI")

care_state$labels_1 <- sprintf("%.01dh%.02d", care_state$score %/% 60, round(care_state$score %% 60))
care_state$labels_2 <- paste0(care_state$score, "%")

color_0 <- "#f79500"
color_1 <- "#F0BD70" 
color_2 <- "#43938A"
color_3 <- "#2F6569"

```

```{r average time patients spent in emergency room}

time_eroom <- care_state %>%
  filter(measure_name == "Average (median) time patients spent in the emergency department before leaving from the visit A lower number of minutes is better") %>%
  mutate(score = score / 60)

time_eroom_map <- left_join(time_eroom, states, by = "state_abbv") 

time_eroom_sub <- time_eroom_map %>%
  select(state_abbv, long, lat)

time_eroom_sub <- na.omit(time_eroom_sub)

cntrd <- function(x) {
  data.frame(centroid(as.matrix(x[,c("long", "lat")])))
}

time_eroom_cent <- data.frame(do.call(rbind, by(time_eroom_sub, time_eroom_sub$state_abbv, cntrd)))

time_eroom_cent <- cbind(state_abbv = rownames(time_eroom_cent), time_eroom_cent)
rownames(time_eroom_cent) <- 1:nrow(time_eroom_cent)

time_eroom_map_labels <- left_join(time_eroom, time_eroom_cent, by = "state_abbv") %>%
  select(state_abbv, lon, lat, labels_1, labels_2, score, state_abbv)

# manually fix AK cent coord
time_eroom_map_labels$lon[1] <- -117.1307
time_eroom_map_labels$lat[1] <- 24.45656

time_eroom_map_labels$labels_1 <- paste0(time_eroom_map_labels$state_abbv, "\n", time_eroom_map_labels$labels_1)

ggplot(time_eroom_map) + 
  geom_polygon(aes(x = long, y = lat, group = group, fill = score), color = "black", size = 0.1) +
  geom_label_repel(data = time_eroom_map_labels, aes(x = lon, y = lat, label = labels_1, fill = score, color = state_abbv == "DC"), size = 2.25, fontface = "bold", family = "Georgia", box.padding = 0.2, label.padding = 0.15, max.overlaps = 20, point.size = NA, label.r = 0, label.size = 0.1, show.legend = FALSE) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 40) +
  scale_fill_gradient(name = "Hours", low = "white", high = color_3, na.value = "#F5F5F5") +
  scale_color_manual(values = c("black", "white")) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  ggtitle("\nEmergency Room Visit Times by State") +
  labs(subtitle = "The median emergency room visit time in the U.S. is about 2h 40m.\nDC has the highest median visit time at 5h 10m.", caption = "Source: Centers for Medicare & Medicaid Services (2023-2024) | github: julia-tache") +
  theme(plot.background = element_rect(fill = "#F5F5F5", color = NA),
        plot.margin = margin(0.25, 0.25, 0.25, 0.25, "cm"),
        panel.background = element_rect(fill = "#F5F5F5", color = NA),
        panel.grid.major = element_line(color = "#F5F5F5"),
        panel.grid.minor = element_line(color = "#F5F5F5"),
        plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size = 12, hjust = 0.5, face = "italic"),
        plot.caption = element_text(size = 10, face = "italic", hjust = 0.5),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = c(0.95, 0.01),
        legend.justification = c("right", "bottom"),
        legend.box.just = "right",
        legend.margin = margin(0, 0, 0, 0),
        legend.background = element_rect(fill = NA),
        legend.title = element_text(size = 10, hjust = 0.5),
        legend.text = element_text(size = 9),
        text = element_text(family = "Georgia", size = 13))

ggsave("time_eroom.png", width = 7, height = 5)
  
```

```{r percent of patients who left before being seen}

care_state %>%
  mutate(score = score / 100) %>%
  filter(measure_name == "Percentage of patients who left the emergency department before being seen Lower percentages are better") %>%
  filter(score > 0.03) %>%
  drop_na(score) %>%
  ggplot(aes(x = reorder(state_abbv, score), y = score, fill = score)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.75) +
  geom_text(aes(label = labels_2), size = 4.5, family = "Georgia", color = "white", fontface = "bold", hjust = 1.5) +
  coord_flip() +
  scale_fill_gradient(name = "Hours", low = color_2, high = color_3, na.value = "#F5F5F5") +
  scale_y_continuous(breaks = seq(0.01, 0.05, 0.01), labels = scales::percent, expand = c(0, 0)) + 
  ggtitle("\nLeft Untreated") +
  labs(subtitle = "States with the highest percentage of patients who left\nthe emergency department before being seen", caption = "Source: Centers for Medicare & Medicaid Services (2023) | github: julia-tache") +
  theme(plot.background = element_rect(fill = "#F5F5F5", color = NA),
        plot.margin = margin(0.25, 0.25, 0.25, 0.6, "cm"),
        panel.background = element_rect(fill = "#F5F5F5", color = NA),
        panel.grid.major = element_line(color = "#F5F5F5"),
        panel.grid.minor = element_line(color = "#F5F5F5"),
        plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size = 12, hjust = 0.5, face = "italic"),
        plot.caption = element_text(size = 10, face = "italic", hjust = 0.5),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 10),
        axis.title.y = element_blank(),
        axis.text.y = element_text(size = 14),
        axis.ticks = element_blank(),
        legend.position = "none",
        text = element_text(family = "Georgia", size = 13))

ggsave("perc_left_eroom.png", width = 7.5, height = 5)

```

```{r providers up-to-date with COVID-19 vaccine}

vaccinations <- care_state %>%
  filter(measure_name == "Percentage of healthcare personnel who are up to date with COVID-19 vaccinations") %>%
  mutate(score = score / 100)

vaccinations_map <- left_join(vaccinations, states, by = "state_abbv") 

vaccinations_sub <- vaccinations_map %>%
  select(state_abbv, long, lat)

vaccinations_sub <-na.omit(vaccinations_sub)

cntrd <- function(x) {
  data.frame(centroid(as.matrix(x[,c("long", "lat")])))
}

vaccinations_cent <- data.frame(do.call(rbind, by(vaccinations_sub, vaccinations_sub$state_abbv, cntrd)))

vaccinations_cent <- cbind(state_abbv = rownames(vaccinations_cent), vaccinations_cent)
rownames(vaccinations_cent) <- 1:nrow(vaccinations_cent)

vaccinations_map_labels <- left_join(vaccinations, vaccinations_cent, by = "state_abbv") %>%
  select(state_abbv, lon, lat, labels_1, labels_2, score)

# manually fix AK cent coord
vaccinations_map_labels$lon[1] <- -117.1307
vaccinations_map_labels$lat[1] <- 24.45656

vaccinations_map_labels$labels_2 <- paste0(vaccinations_map_labels$state_abbv, "\n", vaccinations_map_labels$labels_2)

ggplot(vaccinations_map) + 
  geom_polygon(aes(x = long, y = lat, group = group, fill = score), color = "black", size = 0.1) +
  geom_label_repel(data = vaccinations_map_labels, aes(x = lon, y = lat, label = labels_2, fill = score), color = "black", size = 2.25, fontface = "bold", family = "Georgia", box.padding = 0.2, label.padding = 0.15, max.overlaps = 20, point.size = NA, label.r = 0, label.size = 0.1) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 40) +
  scale_fill_gradient(low = "white", high = color_0, na.value = "#F5F5F5", labels = scales::label_percent()) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  ggtitle("\nCOVID-19 Vaccination Rates: Healthcare Personnel") +
  labs(subtitle = "Percent of healthcare personnel up to date with COVID-19 vaccinations", caption = "Source: Centers for Medicare & Medicaid Services (2024) | github: julia-tache") +
  theme(plot.background = element_rect(fill = "#F5F5F5", color = NA),
        plot.margin = margin(0.25, 0.25, 0.25, 0.25, "cm"),
        panel.background = element_rect(fill = "#F5F5F5", color = NA),
        panel.grid.major = element_line(color = "#F5F5F5"),
        panel.grid.minor = element_line(color = "#F5F5F5"),
        plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size = 12, hjust = 0.5, face = "italic"),
        plot.caption = element_text(size = 10, face = "italic", hjust = 0.5),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = c(0.95, 0.01),
        legend.justification = c("right", "bottom"),
        legend.box.just = "right",
        legend.margin = margin(0, 0, 0, 0),
        legend.background = element_rect(fill = NA),
        legend.title = element_blank(),
        legend.text = element_text(size = 9),
        text = element_text(family = "Georgia", size = 13))

ggsave("vaccinated_perc.png", width = 7.5, height = 5)

```
