---
title: "Tidy Tuesday - Week 5 (2022)"
author: "Julia Tache"
date: "2/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r load data}
library(tidytuesdayR)
library(tidyverse)

breed_traits <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_traits.csv")
trait_description <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/trait_description.csv")
breed_rank_all <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_rank.csv")

head(breed_traits)
head(trait_description)
head(breed_rank_all)
```

```{r}

breed_traits$Breed <- iconv(breed_traits$Breed, from = 'UTF-8', to = 'ASCII//TRANSLIT')

breed_traits$Breed[9] <- "Pointers"

breed_rank_all$Breed[9] <- "Pointers"

breed_rank_all_2020 <- breed_rank_all %>%
  select(Breed, `2020 Rank`)
  
breed_rank_all_2020 <- breed_rank_all_2020[order(breed_rank_all_2020$`2020 Rank`),][1:10, ] # top 10 dog breeds 2020

breed_traits_10 <- breed_traits %>%
 dplyr::filter(Breed == as.character(breed_rank_all_2020$Breed))

breed_traits_10 <- breed_traits_10 %>%
  select(Breed, `Affectionate With Family`, `Shedding Level`, `Trainability Level`, `Energy Level`, `Barking Level`)

breed_traits_10 <- breed_traits_10 %>% remove_rownames %>% column_to_rownames(var = "Breed")

max_min <- data.frame(
  `Affectionate With Family` = c(5, 0), `Shedding Level` = c(5, 0), `Trainability Level` = c(5, 0),
  `Energy Level` = c(5, 0), `Barking Level` = c(5, 0)
)
rownames(max_min) <- c("Max", "Min")

colnames(max_min) <- c("Affectionate With Family", "Shedding Level", "Trainability Level", 
                       "Energy Level", "Barking Level")

# Bind the variable ranges to the data
breed_traits_10 <- rbind(max_min, breed_traits_10)
colnames(breed_traits_10) <- c("Affectionate With Family", "Shedding \nLevel", "Trainability \nLevel", 
                       "Energy \nLevel", "Barking \nLevel")

```

```{r}
library(fmsb)

# helper function from https://www.datanovia.com/en/blog/beautiful-radar-chart-in-r-using-fmsb-and-ggplot-packages/

create_beautiful_radarchart <- function(data, color = "#00AFBB", 
                                        vlabels = colnames(data), vlcex = 0.8,
                                        caxislabels = NULL, title = "title", 
                                        cex.main = 3, ...){
  radarchart(
    data, axistype = 1,
    # Customize the polygon
    pcol = color, pfcol = scales::alpha(color, 0.5), plwd = 2, plty = 1,
    # Customize the grid
    cglcol = "grey", cglty = 1, cglwd = 0.8,
    # Customize the axis
    axislabcol = "grey", 
    # Variable labels
    vlcex = vlcex, vlabels = vlabels,
    caxislabels = caxislabels, title = title, ...
  )
}

library(imager)
img <- load.image("dogs2.png")

par(mar = rep(1, 4))
par(mfrow = c(3, 4))

for(i in 1:10){
  create_beautiful_radarchart(
    data = breed_traits_10[c(1, 2, i+2), ], caxislabels = c(1, 2, 3, 4, 5),
    title = row.names(breed_traits_10)[i+2]
    )
}

library(grid)

grid.raster(img, x=.73, y=.18, width=.275) 
mtext(expression(bold("Traits of Top Ranked Dogs 2020")), side = 3, line = -24, adj = 0.87, cex = 1.1, outer = TRUE)
mtext("Source: AKC | github: julia-tache | Feb 10th, 2022", side = 3, line = -34, adj = 1, cex = .75, outer = TRUE)

```
