---
title: 'Tidy Tuesday - Week #34'
author: "Julia Tache"
date: '2022-08-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r load data}

library(tidytuesdayR)
library(tidyverse)
library(scales)

chips <- read_csv("chip_dataset.csv")

head(chips)

```


```{r clean data}

library(lubridate)

chips <- filter(chips, `Release Date` != "NaT")
chips <- filter(chips, Vendor != "Other")
chips <- filter(chips, `Transistors (million)` > 15) # remove low outliers
chips$Year <- str_extract(chips$`Release Date`, "\\d{4}")
chips$Year <- year(as.Date(chips$Year, format = "%Y"))
chips <- drop_na(chips, `Transistors (million)`)
chips <- drop_na(chips, `Year`)

```


```{r plots}

plot1 <- ggplot(chips, aes(x = Year, y = `Transistors (million)`)) + 
  geom_point(aes(size = `Freq (MHz)`, color = Vendor), alpha = 0.5) +
  facet_grid(~Type) +
  xlab("Year of Release") +
  ylab("Transistors, in millions") +
  ylim(0, 30000) +
  labs(title = "Exponential Growth in GPU Transistors",
       subtitle = "Moore's Law states that the number of transistors in a dense \nintegrated circuit (IC) doubles about every two years. This is especially \ntrue for GPUs, which are lower Frequency than CPUs but catching up.",
       caption = "Source: CHIP Dataset | github: julia-tache | July 26th, 2022") +
  geom_smooth(color = "white", se = FALSE) +
  theme(legend.key = element_rect(fill = "#F0F8FF"),
        legend.background = element_rect(fill="#F0F8FF"),
        legend.title = element_text(color = "black", face = "bold"),
        legend.text = element_text(color = "black"),
        panel.background = element_rect(fill = "#add8e6"),
        legend.position = "bottom",
        plot.background = element_rect(fill = "#F0F8FF"),
        strip.background = element_rect(fill = "#92b1b6"),
        strip.text = element_text(colour = 'black', size = 14, face = "bold"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        plot.title = element_text(hjust = 0, size = 14, face = "bold", color = "black"),
        plot.subtitle = element_text(hjust = 0, size = 10, face = "italic", color = "black"),
        plot.caption = element_text(hjust = 1, color = "black"),
        axis.title.y = element_text(color = "black"),
        axis.text = element_text(color = "black"),
        text = element_text(family = "mono"))

plot_log <- ggplot(chips, aes(x = Year, y = `Transistors (million)`)) + 
  geom_point(aes(size = `Freq (MHz)`, color = Vendor), alpha = 0.5) +
  scale_y_continuous(trans = "log10") +
  facet_grid(~Type) +
  labs(title = "No. of Transistors and Frequency Increasing",
       subtitle = "Moore's Law states that the number of transistors in a dense \nintegrated circuit (IC) doubles about every two years. This is especially \ntrue for GPUs, which are lower Frequency than CPUs but catching up.",
       caption = "Source: CHIP Dataset | github: julia-tache | July 26th, 2022") +
  xlab("Year of Release") +
  ylab("Transistors, in millions \n(base-10 log scale)") +
  ylim(0, 15000) +
  geom_smooth(color = "white", se = FALSE) +
  theme(legend.key = element_rect(fill = "#F0F8FF"),
        legend.background = element_rect(fill="#F0F8FF"),
        legend.title = element_text(color = "black", face = "bold"),
        legend.text = element_text(color = "black"),
        panel.background = element_rect(fill = "#add8e6"),
        plot.background = element_rect(fill = "#F0F8FF"),
        strip.background = element_rect(fill = "#92b1b6"),
        strip.text = element_text(colour = 'black', size = 14, face = "bold"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        plot.title = element_text(hjust = 0, size = 14, face = "bold", color = "black"),
        plot.subtitle = element_text(hjust = 0, size = 10, face = "italic", color = "black"),
        plot.caption = element_text(hjust = 1, color = "black"),
        axis.title.y = element_text(hjust = 0.5, color = "black", size = 10),
        axis.text = element_text(color = "black"),
        text = element_text(family = "mono")) 

```

```{r regular scatter plot}

plot1

ggsave("plot1.png")

```

```{r log scatter plot}

plot_log

ggsave("plot_log.png")

```


